name: nemeeting
description: A new Flutter application.
publish_to: none

version: 4.8.0+40800

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  convert: ^3.1.1
  flutter_datetime_picker: ^1.5.1
  async: ^2.11.0
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  package_info_plus: ^7.0.0
  dio: ^5.4.2+1
  pin_input_text_field: ^4.5.1
  url_launcher: ^6.2.6
  crypto: ^3.0.3
  permission_handler: ^11.3.1

  netease_common: ^1.0.7
  netease_meeting_kit:
    path: ../meeting_kit
  file_picker: ^8.0.0+1

  webview_flutter: ^4.7.0
  sensors_plus: ^5.0.1
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  mask_text_input_formatter: ^2.9.0
  device_info_plus: ^10.1.0
  device_information: ^0.0.4
  sticky_headers: ^0.3.0
#  yunxin_integration_test: 0^0.0.1-rc.7

dependency_overrides:
   device_info_plus: ^10.1.0
   permission_handler: ^11.3.1
   http: ^1.0.0
  # yunxin_event_track:
  #   path: ../yunxin_event_track
  # yunxin_base:
  #   path: ./packages/yunxin_base
  # yunxin_room_kit:
  #   path: ./packages/yunxin_room_kit
  # yunxin_meeting:
  #   path: ./packages/yunxin_meeting
  # yunxin_meeting: ^0.1.0-rc.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/virtual_background_images/images.zip
    - assets/lottie/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

