name: netease_meeting_core
description: A package provide related APIs to start、schedule、join meeting.
version: 0.1.0-rc.0
homepage: https://yunxin.163.com/
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.2
  async: ^2.11.0
  shared_preferences: ^2.2.3
  dio: ^5.4.2+1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  webview_flutter: ^4.7.0
  intl: ^0.18.1
  yunxin_alog: ^2.0.0
  netease_roomkit: ^1.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
